### ISSUE TITLE
Add 3 New Intervals to the existing list

### ISSUE THREAD

**Issue by srPuebla** [brian-the-dev/python-tradingview-ta#105]
Hello Brian,

Is is possible to add the 3 new time intervals to the existing list?
-8 hours
-10 hours
-12 hours

Thanks so much

**Comment by brian-the-dev** [comment]
TL;DR: No.

This library replicates TradingView's technical analysis tab, but without the fancy GUI. It can only give data, indicators, etc available through the site. Since the intervals you mentioned are not available in TradingView, they can't be added to the library.  For reference, this is their page:
![image](https://user-images.githubusercontent.com/40331046/186585471-6d988c1f-77a3-4771-85cf-767077626954.png)
