### ISSUE TITLE
Get some Indicators with Retrieving multiple analysis

### ISSUE THREAD

**Issue by ulinkverse** [brian-the-dev/python-tradingview-ta#110]
I want to get some Indicators with Retrieving multiple analysis
My code:
`from tradingview_ta import *
with open("TA_Token.txt", "r") as t:
    token = [x for x in t.read().splitlines() if x != ""]
with open("TA_Indicators.txt", "r") as i:
    indica = [x for x in i.read().splitlines() if x != ""]

analysis = get_multiple_analysis(
    screener="crypto", 
    interval=Interval.INTERVAL_1_DAY, 
    symbols=token,
    additional_indicators=indica
    )

for key, value in analysis.items():
    print(key)
    print(value.indicators)`

- The results of my code is total indicators. But I just want to get some Indicators. 
- And I need to transfer the results into a single excel file. Please help me!
P/s: Sorry for my bad English

**Comment by brian-the-dev** [comment]
This issue is not related to the library. How you process your data depends on what you need. Since this is your first issue, here's my response:

1. Replace `print(value.indicators)` with `print({k:v for k, v in value.indicators.items() if k in indica}`.
2. [There are a lot of guides online on how to export your data to excel.](https://letmegooglethat.com/?q=export+python+dict+to+excel) Besides, I'm not an excel expert.

I'm closing this issue. Have a good day and good luck with your project!
