### ISSUE TITLE
List of Screeners and Exchanges Table

### ISSUE THREAD

**Issue by alazare619** [brian-the-dev/python-tradingview-ta#42]
I've tried the following but I get errors whenever trying anything other then binance and crypto can we get a table of supported exchange names and screeners

**Comment by brian-the-dev** [comment]
Hi @alazare619,

I'll publish a Google Sheet containing the most popular stock, forex, and crypto later. In the meantime, can you try to run the [quick start](https://python-tradingview-ta.readthedocs.io/en/latest/overview.html#quick-start) code?

**Comment by alazare619** [comment]
AMERICA:

UK:

FOREX:
FX_IDC

CRYPTO:
BINANCE, BINANCEUS, BINGBON, BITBAY, BITCOKE, BITFINEX, BITFLYER, BITTHUMB, BITKUB, BITPANDAPRO, BITSO, BITSTAMP, BITTREX, BTCYOU, BYBIT, CEXIO, COINBASE, COINFLOOR, CURRENCYCOM, CURRENCYCOMLEV, GEMINI, HITBTC, HUOBI, KORBIT, KRAKEN, KUCOIN, MERCADO, OKCOIN, POLONIEX, SUSHISWAP, THEROCKTRADING, TRADESTATION, UNISWAP

CFD:

**Comment by Typhereus** [comment]
BINANCE is working for me but not BINANCEUS. Any ideas?

**Comment by brian-the-dev** [comment]
@Typhereus,

That's from TradingView. They don't have technicals for BinanceUS:

![](https://user-images.githubusercontent.com/40331046/125154071-4e43db00-e182-11eb-918f-5ffbd0fac04c.gif)

**Comment by brian-the-dev** [comment]
Hey everyone! 

It's been more than a month since this issue was created. Sorry to keep you all waiting. I had final exams and didn't have the time to compile a list. 

Today, I just released a website (https://tvdb.brianthe.dev) where you can search for symbols, exchanges, and screeners. If your country isn't listed in the database, please create an issue in this repo: https://github.com/brian-the-dev/tradingview-list.

I'll close this issue.
