### ISSUE TITLE
Is there a way to get the volume indicator?

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [brian-the-dev/python-tradingview-ta#47]
Hi, I wonder if there is a way to get the volume indicator from tradingview?
Thanks,
Daniel

**Comment by brian-the-dev** [comment]
Hi @Daniel-Trung-Nguyen,

For now, you'll need to add a few lines of code to get the volume. Import the `TradingView` class and add the following code before calling `get_analysis()`:
```python
from tradingview_ta import TA_Handler, Interval, TradingView
TradingView.indicators.append("volume{}")
```
For example:
```python
from tradingview_ta import TA_Handler, Interval, TradingView
TradingView.indicators.append("volume{}")

handler = TA_Handler(
    screener="america",
    exchange="nasdaq",
    symbol="TSLA",
    interval=Interval.INTERVAL_1_DAY
)

# Retrieve analysis
analysis = handler.get_analysis()

# Print the volume
print(analysis.indicators["volume"])
```
Not fully tested yet, but it works. I'll consider adding volume in the next version, so you don't have to append `"volume{}"` to the indicators.

If you have any questions, please reply. Otherwise, you may close this issue.

**Comment by Daniel-Trung-Nguyen** [comment]
Awesome. It works. Thank you!
