### ISSUE TITLE
Using Specific indicators

### ISSUE THREAD

**Issue by NightMasterX** [brian-the-dev/python-tradingview-ta#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by NightMasterX** [comment]
Hey, I just wanted to know how we can use RSI 9 and VMWA and turn off all other indicators.

**Comment by brian-the-dev** [comment]
Hey @NightMasterX,

You can update your `tradingview-ta` to version 3.2.5 and use the new function `get_indicators()`. 

Update: `pip install -U tradingview_ta`

TradingView does not support `"RSI9"`, but you can use `"RSI7"`. Code example:

```python
from tradingview_ta import TA_Handler, Interval

handler = TA_Handler(
    symbol="AAPL",
    interval=Interval.INTERVAL_1_DAY,
    screener="america",
    exchange="NASDAQ"
)

x = handler.get_indicators(["RSI7", "VWMA"])
print(x)

# Example output: {'RSI7': 92.77255077, 'VWMA': 133.91506226}
```

See https://pastebin.com/1DjWv2Hd for valid indicators. Documentation coming soon. 

Please reply if you have other questions. Otherwise, you may close this issue.

**Comment by NightMasterX** [comment]
Hi, thanks for informing! New to Stocks and all that, didn't knew it doesn't support RSI9
