### ISSUE TITLE
get_multiple_analysis not working

### ISSUE THREAD

**Issue by thomaspara** [brian-the-dev/python-tradingview-ta#52]
Python version: 3.9.5
tradingview-ta version: 3.2.5

Using the example code:

`from tradingview_ta import *
analysis = get_multiple_analysis(screener="america", interval=Interval.INTERVAL_1_HOUR, symbols=["nasdaq:tsla", "nyse:docn", "nasdaq:aapl"])
`

fails with the following error: 
`
Traceback (most recent call last):
  File "/home/thomas/Documents/Code/stonks/longScalp.py", line 2, in <module>
    analysis = get_multiple_analysis(screener="america", interval=Interval.INTERVAL_1_HOUR, symbols=["nasdaq:tsla", "nyse:docn", "nasdaq:aapl"])
  File "/home/thomas/.local/lib/python3.9/site-packages/tradingview_ta/main.py", line 344, in get_multiple_analysis
    data = TradingView.data(symbols, interval)
TypeError: data() missing 1 required positional argument: 'indicators'`

**Comment by brian-the-dev** [comment]
Hi @thomaspara,

Thanks for notifying me. I'm really sorry because I didn't test `get_multiple_analysis()` in the last update. I've fixed this bug in version 3.2.6. Please update using `pip install -U tradingview_ta`. I also updated the test script so this won't happen again in the future.

If you have questions, please reply. Otherwise, you may close this issue.

**Comment by thomaspara** [comment]
Thank you for the speedy fix.
