### ISSUE TITLE
Can we fetch the current price of the given symbol?

### ISSUE THREAD

**Issue by avatar-lavventura** [brian-the-dev/python-tradingview-ta#56]
I was wondering is it possible to fetch the current price of the given symbol?
That will be a helpful feature during evaluation.

**Comment by brian-the-dev** [comment]
Hi @avatar-lavventura,

Yes, it's possible. You can get opening/closing prices with tradingview-ta (set interval to lowest: 1 minute for near real-time). However, I don't recommend it due to delay (see https://python-tradingview-ta.readthedocs.io/en/latest/faq.html#is-the-data-delayed). If you have an access to an exchange's API, that would be better.

If you still want to, you can modify this code:
```python
from tradingview_ta import TA_Handler, Interval, Exchange

handler = TA_Handler(
    symbol="BTCUSDT",
    screener="crypto",
    exchange="binance",
    interval=Interval.INTERVAL_1_MINUTE
)

analysis = handler.get_analysis()

# Opening price
open_price = analysis.indicators["open"]
print(open_price)
# Output: 38423.76

# Closing price
close_price = analysis.indicators["close"]
print(close_price)
# Output: 38423.76
```

I hope this helps. If you still have questions, please reply. Otherwise, you may close this issue.

**Comment by RaymondTerry** [comment]
After intensive experimenting I found that on average the price is updated about every 27 seconds which isn't terrible to be free and not have to be configured with an external API. This could pair well with the math.isclose() function. This means you can get frequent enough price data updates and a custom actuation tolerance. This could prove useful for something like custom indicator checking, or making checks on the built-in indicators with this project.

Here is an example of what I am talking about:

`def buy_or_sell_btc():

    handler = TA_Handler(
        symbol=BTC,
        screener="crypto",
        exchange="COINBASE",
        interval=Interval.INTERVAL_1_DAY
    )

    analysis = handler.get_analysis()

    blue_line = analysis.indicators["MACD.macd"] #BLUE LINE
    orange_line = analysis.indicators["MACD.signal"] #ORANGE LINE
    rsi = analysis.indicators["RSI"]
    ema_200 = analysis.indicators["EMA200"]
    ema_20 = analysis.indicators["EMA20"]
    ema_50 = analysis.indicators["EMA50"]
    price = analysis.indicators['close']
    
    if blue_line <= 0 and orange_line <= 0 and math.isclose(blue_line, orange_line, abs_tol = 8.00) == True and price < ema_200 and rsi < 50:
        print("GOOD TIME TO DCA BTC")
    else: pass
    
    if blue_line <= 0 and orange_line <= 0 and math.isclose(blue_line, orange_line, abs_tol = 8.00) == True and price > ema_200:
        print("GOOD TIME TO ENTER TRADE")
    else: pass
    
    if blue_line > 0 and orange_line > 0 and math.isclose(blue_line, orange_line, abs_tol = 9.00) == True and price > ema_200:
        print("GOOD TIME TO TAKE PROFIT BTC")
    else: pass

    if math.isclose(ema_20, ema_50, abs_tol = 50.00) == True:
        print("GOLDEN CROSS OR BEARISH CROSS FOR BTC")
    else: pass`

**Comment by avatar-lavventura** [comment]
@RaymondTerry Thank you for your valuable time. 27 second interval is reasonable on my end. On the example why did you keep the interval as 1 day (`interval=Interval.INTERVAL_1_DAY`), can we keep it as 1 minute?

=> An example to fetch data for for the close price for Silver/USD would be also helpful.Its link (https://www.tradingview.com/chart/bHXZrXAy/?symbol=TVC%3ASILVER)? I believe its symbol is `SILVER`.

**Comment by oskvr37** [comment]
**binance api** makes it possible to get latest price of given symbol and i think its the best way to do it:

```
from requests import get

def get_price(symbol):
    url = f'https://api.binance.com/api/v1/ticker/price?symbol={symbol}'
    request = get(url)
    price = float(loads(request.text)['price'])
    return price
```

**Comment by avatar-lavventura** [comment]
@oskvr37 I don't want crypto pairs. I just want to get close prices of Silver, Gold US Stocks

**Comment by RaymondTerry** [comment]
@oskvr37 
> @RaymondTerry Thank you for your detalied answer. 27 second interval is reasonable on my end. On the example why did you keep the interval as 1 day (`interval=Interval.INTERVAL_1_DAY`), can we keep it as 1 minute, or 15 minute?
> 
> Could you also provide an example for:
> => How to fetch close price of Silver/USD? Its link is (https://www.tradingview.com/chart/bHXZrXAy/?symbol=TVC%3ASILVER). I believe its symbol is `SILVER`.
> 
> I was able to get Silver's price from yahoo finance, but I am not sure how othen does Yahoo updates prices.
> 
> ```
> import yfinance as yf
> 
> def get_silver() -> float:
>     """Return silver price."""
>     msft = yf.Ticker("SI=F")
>     info = msft.info
>     silver_oz_price = info["regularMarketPrice"]
> ```



To be more detailed I found when calling a function outside of a file that uses at least the daily time frame or the minute time frame that they get updated on average every 27 seconds. I have not tested any of the other time frames. This may be because regardless of what timeframe it is set to the "close" might be considered whatever the current price is at the time the function is called, which makes it so that each time the function is called it is updated just as frequent as any time frame. That is only my theory so far. What makes this very odd is that when consecutively calling the function in the _**same file on the daily time frame**_ it sometimes does not get updated as frequently.  Something else I noticed is that it will get updated if you manually call the function, but in a loop it will eventually.
 

Here is an example to try:
_**tradingview_test.py**_
```
from tradingview_ta import *
import time

def buy_or_sell():

    handler = TA_Handler(
        symbol="BTCUSD",
        screener="crypto",
        exchange="COINBASE",
        interval=Interval.INTERVAL_1_DAY
    )

    analysis = handler.get_analysis()

    price = analysis.indicators['close']

    
    print(price)
    print(btc_price())



def btc_price():
    

    btc_price = TA_Handler(
        symbol="BTCUSD",
        screener="crypto",
        exchange="COINBASE",
        interval=Interval.INTERVAL_1_MINUTE
    )


    analysis = btc_price.get_analysis()

    price = analysis.indicators['close']

    return price
```
if you run _buy_or_sell()_ in a loop with a 27 second pause you should see the daily one stay the same longer than the minute. 


interval_should_update_here.py
```
import tradingview_test
import time

def tvt():
    tradingview_test.buy_or_sell()





starttime = time.time()

while(True):
    tvt()
    time.sleep(27.0 - ((time.time() - starttime) % 27.0))

```
If you run this one which calls the function outside of the originating file they will both update just as frequently however. It is hard to explain this behavior, I don't even understand it and it could be coincidence for all I know. 


As far as getting the price of silver and gold you will be looking at something like this:

Gold symbol: GC1!
- Same exchange
```
def silver_price():

    handler = TA_Handler(
        symbol="SI1!",
        screener="america",
        exchange="COMEX",
        interval=Interval.INTERVAL_1_MINUTE
    )

    analysis = handler.get_analysis()

    price = analysis.indicators['close']

    print(price)

```
Unfortunately the futures is all they have available to scrape so far it seems. I also am looking for a way to get the total altcoin market cap for crypto and the total crypto market cap but it doesn't seem this project can scrape the indexes. The bitcoin dominance would also be useful as well.

**Comment by avatar-lavventura** [comment]
@RaymondTerry For total total altcoin market cap, you can use [`ccxt`](https://github.com/ccxt/ccxt). I am fetching binance's data with `async` calls and its better than tradingview I believe, I can make call in every 10 ms.

Here is its example code, not sure it has total cap tho.
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-ticker-continuously.py

**Comment by RaymondTerry** [comment]
@avatar-lavventura Thank you for that resource. Currently I am working on a personal project that solely relies on preconfigured data sources(i.e not API's which require individual keys) and tradingview_ta seems to be a great one.  I will start uploading it when there is enough features. It essentially is a passive signal bot that checks for indicator value conditions to be met and sends sms alerts when the predetermined conditions are met. The only configuration it requires is a phone number and gmail account.

**Comment by avatar-lavventura** [comment]
@RaymondTerry  Why do you send a sms alert? Instead you should sent a webhook into a your Python Flask server which can redirect it into your discord channel, which is the way I am doing.

**Comment by RaymondTerry** [comment]
@avatar-lavventura I did look into that, sms just seemed more convenient and more easily configurable for average users. Best of all sms is optional, so I can still add something like that to make a centralized channel that gets signal alerts for more than generally one person at a time. I think I'll actually integrate that. If you want I could even integrate it with yours seeing as I am less familiar with custom discord bots.
