### ISSUE TITLE
How do I retrieve the candlestick pattern indicators?

### ISSUE THREAD

**Issue by lbzt** [brian-the-dev/python-tradingview-ta#80]
**Is your feature request related to a problem? Please describe.**
Hi, I have difficulties retrieving candlestick patterns when using tradingview_ta. I tried using the add_indicators function, but it doesn't work as expected.

**Describe the solution you'd like**
Can you help me by giving the basic example of retrieving candlestick patterns? Thanks.

**Comment by brian-the-dev** [comment]
Hi @lbzt,

Please see https://pastebin.com/1DjWv2Hd for available indicators. To retrieve the candlestick patterns, use the indicators that start with `Candle`. If the value is zero, then the pattern isn't detected. Example:

```python
from tradingview_ta import TA_Handler, Interval

handler = TA_Handler(
    screener="crypto",
    interval= Interval.INTERVAL_1_HOUR,
    symbol="BTCUSDT",
    exchange="binance",
)
handler.add_indicators([
  "Candle.AbandonedBaby.Bearish",
  "Candle.AbandonedBaby.Bullish",
  "Candle.Engulfing.Bearish",
  "Candle.Harami.Bearish",
  "Candle.Engulfing.Bullish",
  "Candle.Harami.Bullish",
  "Candle.Doji",
  "Candle.Doji.Dragonfly",
  "Candle.EveningStar",
  "Candle.Doji.Gravestone",
  "Candle.Hammer",
  "Candle.HangingMan",
  "Candle.InvertedHammer",
  "Candle.Kicking.Bearish",
  "Candle.Kicking.Bullish",
  "Candle.LongShadow.Lower",
  "Candle.LongShadow.Upper",
  "Candle.Marubozu.Black",
  "Candle.Marubozu.White",
  "Candle.MorningStar",
  "Candle.ShootingStar",
  "Candle.SpinningTop.Black",
  "Candle.SpinningTop.White",
  "Candle.3BlackCrows",
  "Candle.3WhiteSoldiers",
  "Candle.TriStar.Bearish",
  "Candle.TriStar.Bullish"
])
analysis = handler.get_analysis()

pattern_count = 0

for key, value in analysis.indicators.items():
    if "Candle" in key:
        if value == 1:
            print("{} candlestick pattern detected".format(key))
            pattern_count += 1

if pattern_count == 0:
    print("No candlestick patterns detected")

# Example output: 
# "Candle.AbandonedBaby.Bearish candlestick pattern detected" OR
# "No candlestick patterns detected"
```

You can modify the code as needed, but that's the basic. If you still have questions, don't hesitate to reply. Otherwise, you can close this issue. Have a nice day and good luck with your project!

P.S. I noticed that this is your first issue on GitHub. Next time, try filling in the issue template correctly instead of typing everything in the title. I edited your issue as an example of how to create an issue that's clear and comprehensible.

**Comment by lbzt** [comment]
HI @brian-the-dev,
thank you very mutch for the quick reply. Now it is more clear! :-) 
I am sorry if i wrote the whole issue in the title. i'll try to be better next time!
Wish you All the best!

**Comment by Magiccode2022** [comment]
hello.How to get previously closed candlestick information about what candlestick pattern occurred
