### ISSUE TITLE
Set only some indicators instead of add_indicators

### ISSUE THREAD

**Issue by martinbouhier** [brian-the-dev/python-tradingview-ta#87]
How can I set only a list of indicators like the example below.

The answer I'm looking for is
` >>> LUNAUSDT :  {'RECOMMENDATION': 'BUY', 'BUY': 2}`
Thanks

```
hndler = TA_Handler(
        symbol=value['symbol'],
        screener=value['screener'],
        exchange=value['exchange'],
        interval=Interval.INTERVAL_1_MINUTE
)
x = handler.get_indicators(["RSI","ADX"])
summary = handler.get_analysis().summary

>>> {'RSI': 15.46198807, 'ADX': 35.47608119}
>>> LUNAUSDT :  {'RECOMMENDATION': 'SELL', 'BUY': 5, 'SELL': 10, 'NEUTRAL': 11}
```

**Comment by brian-the-dev** [comment]
HI @martinbouhier,

So you only want to get the analysis for certain indicators? The summary variable is designed to return the exact data TradingView displays on their site. However, you can access the individual analysis through the `oscillators` and `moving_averages` variables. Example:
```python
x = handler.get_analysis()
print(f'RSI value: {x.indicators["RSI"]}, recommendation: {x.oscillators["COMPUTE"]["RSI"]}')
# Output: RSI value: 63.03884747, recommendation: NEUTRAL
print(f'ADX value: {x.indicators["ADX"]}, recommendation: {x.oscillators["COMPUTE"]["ADX"]}')
# Output: ADX value: 22.48391738, recommendation: NEUTRAL
```

You can modify the code to count the number of BUY, NEUTRAL, and SELL and check which has the highest value.

If you have further questions, please reply to my comment. Otherwise, you may close this issue. Have a good one!

**Comment by martinbouhier** [comment]
Thanks Brian! That is exactly what I was looking for!
