### ISSUE TITLE
Working with support and resistance levels

### ISSUE THREAD

**Issue by Magiccode2022** [brian-the-dev/python-tradingview-ta#98]
Hello
We are trading with candlestick patterns, how can we find the resistance and support of desires in different time frames. What valid code or strong indicator is there in this library and which one do you recommend?
Thanks

**Comment by brian-the-dev** [comment]
Due to the API's lack of historical data, the tradingview-ta library does not assist in determining resistance and support levels. Instead, try [tvdatafeed](https://github.com/StreamAlpha/tvdatafeed) which is a library that supports downloading historical data. There are a lot of codes online to determine resistance and support levels. I'm not algotrading anymore so I can't recommend any indicator.

**Comment by Magiccode2022** [comment]
Very thanks
